### ISSUE TITLE
Enable Prometheus metrics

### ISSUE THREAD

**Issue by cbcoutinho** [jellyfin/jellyfin-helm#28]
I would like to simplify metrics collection for Jellyfin using this Helm chart, as Jellyfin currently supports exposing Prometheus metrics, although this functionality is currently disabled by default in the upstream image.

This is how I'm currently working around the limitation in the helm chart, based on #27; however, I'm open to improvements.

```yaml
# values.yaml
  image:
    command:
      - bash
      - '-c'
      - >-
        sed 's,<EnableMetrics>false</EnableMetrics>,<EnableMetrics>true</EnableMetrics>,' -i /config/config/system.xml &&
        /jellyfin/jellyfin
```

As well as creating a ServiceMonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin-svc-monitor
  namespace: jellyfin
  labels:
    release: observability
spec:
  namespaceSelector:
    matchNames:
      - jellyfin
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
```
