### ISSUE TITLE
add nfs mount type

### ISSUE THREAD

**Issue by lknite** [jellyfin/jellyfin-helm#43]
Recently I installed 'radarr' and 'sonarr' via the truechart helm chart.

Check out this magic:
```
  persistence:
    sabnzbd-data:
      enabled: true
      type: nfs
      path: /nfs/sabnzbd
      server: 10.0.0.11
      mountPath: /app-sabnzbd
    tower-data:
      enabled: true
      type: nfs
      path: /nfs/media
      server: 10.0.0.11
      mountPath: /data-tower
```

This resulted in two nfs mounts without any pvcs.

Perhaps something similar could be implemented with jellyfin?  It is interesting how it works without a pvc using the built in nfs type.

Reference helm chart:
https://github.com/truecharts/public/tree/master/charts/stable/radarr

They use a common library:
https://github.com/truecharts/public/blob/master/charts/library/common/values.yaml
