### ISSUE TITLE
(Question) Mount media from NFS

### ISSUE THREAD

**Issue by tobiasbartel** [jellyfin/jellyfin-helm#46]
Hello,

quick question, I have all my media on a NAS shared via NFS.
What do I have to put into the values file in order to make the NFS shares available in the container?

Thanks in advance!

Cheers!

**Comment by astephon88** [comment]
First you would need to create a PV on the cluster pointing to your nfs share:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-library-storage-pv
spec:
  accessModes:
  - ReadWriteMany
  nfs:
    server: nfs_server_hostname
    path: "/path/to/your/media"
  mountOptions:
      - nfsvers=4.1 # or whatever NFS version you're running
  capacity:
    storage: 26Ti # max capacity of the NFS share, or less if you want to limit how much storage the app sees as available 
``` 

Then create a PVC in the namespace that jellyfin will deploy to referencing that PV (you'll need to create the namespace first):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-library-storage-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 26Ti # match the storage amount from the PV
  volumeName: jellyfin-library-storage-pv
```

Finally, add `jellyfin-library-storage-pvc` to `persistence.media.existingClaim` in your values file

**Comment by alexmorbo** [comment]
Hi,

I have a similar issue. Currently, I mount media to hostPath, but now I need to mount it to a different directory, such as /share, and I cannot name the volume "media."

Would the following change in the chart resolve the issue?

```
{{- if .Values.persistence.media.enabled }}
- name: media
  persistentVolumeClaim:
    claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{- else }}{{ template "jellyfin.fullname" . }}-media{{- end }}
  emptyDir: {}
{{- end }}
```

Changes:
- Move the condition statement outside the "media" definition.

**Comment by Supporterino** [comment]
Hey @tobiasbartel  @alexmorbo @astephon88,

no need to create a extra PV for your NFS share. The media PVC for jellyfin is for the media produced by jellyfin like thumbnails and stuff. To mount your own media into jellyfin you can utilise the `volumes` and `volumeMounts` keys like this:

```yaml
volumes:
  - name: series
    nfs:
      server: 1.2.3.4
      path: /some/path/series
  - name: movies
    nfs:
      server: 1.2.3.4
      path: /some/path/movies

volumeMounts:
  - mountPath: /series
    name: series
  - mountPath: /movies
    name: movies
    readOnly: true
```
