### ISSUE TITLE
QSV and VA-API codecs.

### ISSUE THREAD

**Issue by dawsmac** [jellyfin/jellyfin-helm#47]
Hey all, 

Trying to get the QSV and VA-API codecs accessable via Jellyfin using Helm. I have confirmed everything is fine on my nodes and the CPU does support the GPU Codeces 

```
 ls -l /dev/dri/renderD128
crw-rw---- 1 root render 226, 128 Dec 30 10:02 /dev/dri/renderD128
~$ getent group render 
render:x:993:
```

```
 k exec -it --namespace mediaplayer jellyfin-64d59c5c58-dj6hz -- /usr/lib/jellyfin-ffmpeg/vainfo 
Trying display: drm
error: failed to initialize display
command terminated with exit code 1
```

My vaules.yaml

```
jellyfin:
  config:
    transcodeFolder: "/tmp/jellyfin-transcodes"

replicaCount: 1

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 1Gi
    cpu: 1
  limits:
    memory: 1Gi
    cpu: 1

persistence:
  enabled: true
  config:
    enabled: true
    existingClaim: jellyfin-pvc-config
  media:
    enabled: true
    existingClaim: nfs-pvc-media-data

extraVolumes:
- name: "render-device"
  hostPath:
    path: "/dev/dri/renderD128"

extraVolumeMounts:
- name: "render-device"
  mountPath: "/dev/dri/renderD128"

service:
  type: ClusterIP
  port: 8096

nodeSelector:
  jellyfin: "true"

dnsPolicy: ClusterFirst

ingressRoute:
  enabled: true
  name: jellyfin-ingressroute
  annotations:
    kubernetes.io/ingress.class: traefik
  entryPoints:
  - websecure
  routes:
  - match: Host(`jellyfin.home.local`)
    kind: Rule
    services:
    - name: jellyfin
      port: 8096
  tls:
    certResolver: ****

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  supplementalGroups:
  - 993

podSecurityContext:
  supplementalGroups:
  - 993
  fsGroup: 993

```
