### ISSUE TITLE
cannot provide a pvc for the cache

### ISSUE THREAD

**Issue by jpnadas** [jellyfin/jellyfin-helm#62]
As far as I can tell from reading the values file, it's not possible to give a separate pvc for cache.

It would be nice to be able to do that when running on hosts that are booted from SD cards, to avoid wear.

**Comment by JoVoCop** [comment]
While the cache volume isn't baked into the chart like `media` and `config`, you can still provide a cache directory via `.Values.volumes` and `.Values.volumeMounts` ([values reference](https://github.com/jellyfin/jellyfin-helm/blob/0fcf1d2206aa845bbcac536653475d925d5b2cb2/charts/jellyfin/values.yaml#L140-L151)) like this:


```
volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: my-pvc

volumeMounts:
  - name: cache
    mountPath: /cache
```

**Comment by jpnadas** [comment]
Thanks, that's a good suggestion. Is it an idea to include it in the values configurations similar to `media` and `config`?

if so, I am happy to create a PR myself. Cheers!

**Comment by lexfrei** [comment]
This feature has been implemented in PR #88.

The chart now supports dedicated cache volume persistence with the same flexibility as config and media volumes:

**Configuration options:**
- **PVC** (default type): Creates a PersistentVolumeClaim for cache storage
- **hostPath**: Direct mount from host filesystem
- **emptyDir**: Default when disabled (maintains backward compatibility)

**Example configuration:**
```yaml
persistence:
  cache:
    enabled: true
    type: pvc
    size: 10Gi
    storageClass: fast-ssd  # optional
```

**For SD card hosts (like Raspberry Pi):**
```yaml
persistence:
  cache:
    enabled: true
    type: hostPath
    hostPath: /mnt/usb-drive/jellyfin-cache
```

The cache volume is disabled by default, so existing users will see no changes. The feature will be available once PR #88 is merged.

Cache will be mounted at `/cache` inside the Jellyfin container.
